In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import geopandas as gp
from geopandas import GeoDataFrame

In [2]:
# load shp file extracted from zipfile
# Geopandas geometry
prec_shp = gp.read_file("Resources/bdry_votingdistricts.shp" )
prec_shp

,VTDID,PCTNAME,PCTCODE,SHORTLABEL,MCDNAME,MCDCODE,MCDFIPS,MCDGNIS,CTU_TYPE,COUNTYNAME,...,CTYCOMDIST,JUDDIST,SWCDIST,SWCDIST_N,WARD,HOSPDIST,HOSPDIST_N,PARKDIST,PARKDIST_N,geometry
0,271730045,Friendship Twp,0045,None,Friendship Twp,035,22832,00664234,township,Yellow Medicine,...,3,08,5173,Yellow Medicine,None,None,None,None,None,"POLYGON ((284369.269 4964918.229, 284321.301 4..."
1,270910110,Galena Twp,0110,None,Galena Twp,055,23030,00664240,township,Martin,...,5,05,6091,Martin,None,None,None,None,None,"POLYGON ((362977.491 4856419.851, 362974.359 4..."
2,270930045,Darwin Twp,0045,None,Darwin Twp,040,14860,00663929,township,Meeker,...,1,08,2093,Meeker,None,None,None,None,None,"POLYGON ((391605.300 5000799.731, 391581.799 4..."
3,271370060,Biwabik Twp,0060,None,Biwabik Twp,060,06166,00663605,township,St. Louis,...,4,06,3137,North St. Louis,None,None,None,None,None,"MULTIPOLYGON (((544403.320 5260705.800, 544214..."
4,270010015,Ball Bluff Twp,0015,None,Ball Bluff Twp,015,03358,00663498,township,Aitkin,...,5,09,3001,Aitkin,None,None,None,None,None,"POLYGON ((485475.521 5207980.031, 485475.766 5..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4105,270950015,Borgholm Twp,0015,None,Borgholm Twp,015,07012,00663634,township,Mille Lacs,...,4,07,3095,Mille Lacs,None,1320,Milaca Area,None,None,"MULTIPOLYGON (((450879.660 5068471.679, 451005..."
4106,270530505,Corcoran P-2,0505,P-2,Corcoran,030,13168,02393634,city,Hennepin,...,7,04,None,None,None,None,None,1,Three Rivers Park District,"POLYGON ((455732.119 5000074.516, 457351.820 5..."
4107,271710005,Albertville P-1,0005,P-1,Albertville,005,00730,02393904,city,Wright,...,4,10,4171,Wright,None,None,None,None,None,"POLYGON ((447828.738 5007699.654, 447826.627 5..."
4108,271710127,Monticello P-2,0127,P-2,Monticello,109,43774,02395385,city,Wright,...,2,10,4171,Wright,None,1330,Monticello-Big Lake Community,None,None,"POLYGON ((439564.488 5015565.645, 439569.764 5..."
4109,271410120,Big Lake Twp P-2,0120,P-2,Big Lake Twp,020,05770,00663589,township,Sherburne,...,2,10,4141,Sherburne,None,1330,Monticello-Big Lake Community,None,None,"MULTIPOLYGON (((447091.451 5019270.882, 447094..."

In [3]:
# Rename the columns that I'm going to keep
prec_shp = prec_shp.rename(columns = {'PCTNAME': 'precinct',
                                      'COUNTYFIPS': 'county_fips'})
prec_shp.head()

,VTDID,precinct,PCTCODE,SHORTLABEL,MCDNAME,MCDCODE,MCDFIPS,MCDGNIS,CTU_TYPE,COUNTYNAME,...,CTYCOMDIST,JUDDIST,SWCDIST,SWCDIST_N,WARD,HOSPDIST,HOSPDIST_N,PARKDIST,PARKDIST_N,geometry
0,271730045,Friendship Twp,0045,None,Friendship Twp,035,22832,00664234,township,Yellow Medicine,...,3,08,5173,Yellow Medicine,None,None,None,None,None,"POLYGON ((284369.269 4964918.229, 284321.301 4..."
1,270910110,Galena Twp,0110,None,Galena Twp,055,23030,00664240,township,Martin,...,5,05,6091,Martin,None,None,None,None,None,"POLYGON ((362977.491 4856419.851, 362974.359 4..."
2,270930045,Darwin Twp,0045,None,Darwin Twp,040,14860,00663929,township,Meeker,...,1,08,2093,Meeker,None,None,None,None,None,"POLYGON ((391605.300 5000799.731, 391581.799 4..."
3,271370060,Biwabik Twp,0060,None,Biwabik Twp,060,06166,00663605,township,St. Louis,...,4,06,3137,North St. Louis,None,None,None,None,None,"MULTIPOLYGON (((544403.320 5260705.800, 544214..."
4,270010015,Ball Bluff Twp,0015,None,Ball Bluff Twp,015,03358,00663498,township,Aitkin,...,5,09,3001,Aitkin,None,None,None,None,None,"POLYGON ((485475.521 5207980.031, 485475.766 5..."

In [4]:
# Only need 3 columns
prec_shp = prec_shp[['precinct', 'county_fips', 'geometry']]
prec_shp

,precinct,county_fips,geometry
0,Friendship Twp,173,"POLYGON ((284369.269 4964918.229, 284321.301 4..."
1,Galena Twp,091,"POLYGON ((362977.491 4856419.851, 362974.359 4..."
2,Darwin Twp,093,"POLYGON ((391605.300 5000799.731, 391581.799 4..."
3,Biwabik Twp,137,"MULTIPOLYGON (((544403.320 5260705.800, 544214..."
4,Ball Bluff Twp,001,"POLYGON ((485475.521 5207980.031, 485475.766 5..."
...,...,...,...
4105,Borgholm Twp,095,"MULTIPOLYGON (((450879.660 5068471.679, 451005..."
4106,Corcoran P-2,053,"POLYGON ((455732.119 5000074.516, 457351.820 5..."
4107,Albertville P-1,171,"POLYGON ((447828.738 5007699.654, 447826.627 5..."
4108,Monticello P-2,171,"POLYGON ((439564.488 5015565.645, 439569.764 5..."
4109,Big Lake Twp P-2,141,"MULTIPOLYGON (((447091.451 5019270.882, 447094..."

In [5]:
# New csv file that has the correct precinct names that align with the geopandas shape files
# Set file path
csvpath = "Resources/2016_precincts_newVersion.csv"

# Read csv and preview dataframe
prec_df = pd.read_csv(csvpath, encoding="ISO-8859-1")
pd.set_option('display.max_columns', None)
prec_df.head()

,VTDID,PCTNAME,PCTCODE,MCDNAME,COUNTYNAME,COUNTYCODE,CONGDIST,MNSENDIST,MNLEGDIST,CTYCOMDIST,JUDDIST,SWCDIST,WARD,HOSPDIST,PARKDIST,TABSYSTEM,TABMODEL,MAILBALLOT,REG7AM,EDR,SIGNATURES,AB_MB,FEDONLYAB,PRESONLYAB,TOTVOTING,USPRSR,USPRSDFL,USPRSCP,USPRSLMN,USPRSSWP,USPRSGP,USPRSADP,USPRSIP,USPRSLIB,USPRSWI,USPRSTOTAL,USREPR,USREPDFL,USREPWI,USREPTOTAL,MNSENR,MNSENDFL,MNSENWI,MNSENTOTAL,MNLEGR,MNLEGDFL,MNLEGWI,MNLEGTOTAL,MNCA1YES,MNCA1NO,MNCA1EST,MNCA1TOTAL
0,270010005.0,Aitkin,5.0,Aitkin,Aitkin,1.0,8.0,10.0,10B,1.0,9.0,3001.0,NaN,NaN,NaN,Precinct Tabulator,ES&S Model 100,NO,1141,110,758,242,0,0,1000,552,358,3,7,1,2,0,21,36,6,986,491,470,0,961,574,368,1,943,561,411,0,972,731,224,45,1000
1,270010010.0,Aitkin Twp,10.0,Aitkin Twp,Aitkin,1.0,8.0,10.0,10B,1.0,9.0,3001.0,NaN,NaN,NaN,Precinct Tabulator,ES&S Model 100,NO,588,44,437,113,0,0,550,356,154,1,2,0,5,0,7,18,4,547,332,206,0,538,381,150,0,531,370,173,0,543,438,95,17,550
2,270010015.0,Ball Bluff Twp,15.0,Ball Bluff Twp,Aitkin,1.0,8.0,10.0,10B,5.0,9.0,3001.0,NaN,NaN,NaN,Precinct Tabulator,ES&S Model 100,NO,179,18,145,19,0,0,164,96,57,0,1,0,1,0,2,6,1,164,80,82,0,162,83,77,0,160,79,79,0,158,131,32,1,164
3,270010020.0,Balsam Twp,20.0,Balsam Twp,Aitkin,1.0,8.0,10.0,10B,5.0,9.0,3001.0,NaN,NaN,NaN,Central Count,ES&S Model 100,YES,22,0,0,19,0,0,19,9,8,0,0,0,0,0,0,0,1,18,9,10,0,19,10,9,0,19,8,11,0,19,15,2,2,19
4,270010025.0,Beaver Twp,25.0,Beaver Twp,Aitkin,1.0,8.0,10.0,10B,3.0,9.0,3001.0,NaN,NaN,NaN,Central Count,ES&S Model 100,YES,42,0,0,37,0,0,37,16,19,0,2,0,0,0,0,0,0,37,11,25,0,36,13,20,0,33,11,23,0,34,31,6,0,37

In [6]:
# Get rid of columns
prec_df = prec_df[['VTDID', 'PCTNAME', 'PCTCODE', 'MCDNAME', 'COUNTYNAME', 'COUNTYCODE',
                   'USPRSR', 'USPRSDFL', 'USPRSTOTAL']][:-1]
prec_df

,VTDID,PCTNAME,PCTCODE,MCDNAME,COUNTYNAME,COUNTYCODE,USPRSR,USPRSDFL,USPRSTOTAL
0,270010005.0,Aitkin,5.0,Aitkin,Aitkin,1.0,552,358,986
1,270010010.0,Aitkin Twp,10.0,Aitkin Twp,Aitkin,1.0,356,154,547
2,270010015.0,Ball Bluff Twp,15.0,Ball Bluff Twp,Aitkin,1.0,96,57,164
3,270010020.0,Balsam Twp,20.0,Balsam Twp,Aitkin,1.0,9,8,18
4,270010025.0,Beaver Twp,25.0,Beaver Twp,Aitkin,1.0,16,19,37
...,...,...,...,...,...,...,...,...,...
4115,271730145.0,Swede Prairie Twp,145.0,Swede Prairie Twp,Yellow Medicine,87.0,44,13,61
4116,271730150.0,Tyro Twp,150.0,Tyro Twp,Yellow Medicine,87.0,77,19,97
4117,271730155.0,Wergeland Twp,155.0,Wergeland Twp,Yellow Medicine,87.0,81,24,110
4118,271730160.0,Wood Lake,160.0,Wood Lake,Yellow Medicine,87.0,138,51,209
4119,271730165.0,Wood Lake Twp,165.0,Wood Lake Twp,Yellow Medicine,87.0,96,23,130

In [7]:
# Rename columns
prec_df = prec_df.rename(columns = {'MCDNAME': 'Munic/Unorg Terr Name',
                                    'USPRSR': 'Trump', 'USPRSDFL': 'Clinton',
                                    'USPRSTOTAL': 'Total Votes'})
prec_df

,VTDID,PCTNAME,PCTCODE,Munic/Unorg Terr Name,COUNTYNAME,COUNTYCODE,Trump,Clinton,Total Votes
0,270010005.0,Aitkin,5.0,Aitkin,Aitkin,1.0,552,358,986
1,270010010.0,Aitkin Twp,10.0,Aitkin Twp,Aitkin,1.0,356,154,547
2,270010015.0,Ball Bluff Twp,15.0,Ball Bluff Twp,Aitkin,1.0,96,57,164
3,270010020.0,Balsam Twp,20.0,Balsam Twp,Aitkin,1.0,9,8,18
4,270010025.0,Beaver Twp,25.0,Beaver Twp,Aitkin,1.0,16,19,37
...,...,...,...,...,...,...,...,...,...
4115,271730145.0,Swede Prairie Twp,145.0,Swede Prairie Twp,Yellow Medicine,87.0,44,13,61
4116,271730150.0,Tyro Twp,150.0,Tyro Twp,Yellow Medicine,87.0,77,19,97
4117,271730155.0,Wergeland Twp,155.0,Wergeland Twp,Yellow Medicine,87.0,81,24,110
4118,271730160.0,Wood Lake,160.0,Wood Lake,Yellow Medicine,87.0,138,51,209
4119,271730165.0,Wood Lake Twp,165.0,Wood Lake Twp,Yellow Medicine,87.0,96,23,130

In [8]:
# Make percentage columns for Trump and Clinton
prec_df['Trump %'] = ((prec_df['Trump'] / prec_df['Total Votes']) * 100).round(2)
prec_df['Clinton %'] = ((prec_df['Clinton'] / prec_df['Total Votes']) * 100).round(2)
prec_df

,VTDID,PCTNAME,PCTCODE,Munic/Unorg Terr Name,COUNTYNAME,COUNTYCODE,Trump,Clinton,Total Votes,Trump %,Clinton %
0,270010005.0,Aitkin,5.0,Aitkin,Aitkin,1.0,552,358,986,55.98,36.31
1,270010010.0,Aitkin Twp,10.0,Aitkin Twp,Aitkin,1.0,356,154,547,65.08,28.15
2,270010015.0,Ball Bluff Twp,15.0,Ball Bluff Twp,Aitkin,1.0,96,57,164,58.54,34.76
3,270010020.0,Balsam Twp,20.0,Balsam Twp,Aitkin,1.0,9,8,18,50.00,44.44
4,270010025.0,Beaver Twp,25.0,Beaver Twp,Aitkin,1.0,16,19,37,43.24,51.35
...,...,...,...,...,...,...,...,...,...,...,...
4115,271730145.0,Swede Prairie Twp,145.0,Swede Prairie Twp,Yellow Medicine,87.0,44,13,61,72.13,21.31
4116,271730150.0,Tyro Twp,150.0,Tyro Twp,Yellow Medicine,87.0,77,19,97,79.38,19.59
4117,271730155.0,Wergeland Twp,155.0,Wergeland Twp,Yellow Medicine,87.0,81,24,110,73.64,21.82
4118,271730160.0,Wood Lake,160.0,Wood Lake,Yellow Medicine,87.0,138,51,209,66.03,24.40
4119,271730165.0,Wood Lake Twp,165.0,Wood Lake Twp,Yellow Medicine,87.0,96,23,130,73.85,17.69

In [13]:
len(prec_df['PCTNAME'])

4120